import pandas as pd
import Protein


aa_df = pd.read_csv("../data/amino_acid_properties.csv")
aa_hydropathy = dict()
aa_pI = dict()
aa_Surface = dict()

for pos, aa in enumerate(aa_df["1-letter code"]):
    aa_hydropathy[aa] = aa_df["hydropathy index (Kyte-Doolittle method)"][pos]
    aa_pI[aa] = aa_df["pI"][pos]
    aa_Surface = aa_df["Accessible surface"][pos]
lookup = {"hydropathy":aa_hydropathy, "pI":aa_pI}



def test_get_data():
    GPCR = Protein.exercise_5.Protein(lookup)
    GPCR.get_data("P32248", "GPCR")
    Receptor = Protein.exercise_5.Protein(lookup)
    Receptor.get_data("Q8MLW0", "Receptor-tyrosin-kinase")

    assert GPCR.sequence.startswith(">") is False
    assert Receptor.sequence.startswith(">") is False

    assert GPCR.sequence == """MDLGKPMKSVLVVALLVIFQVCLCQDEVTDDYIGDNTTVDYTLFESLCSKKDVRNFKAWFLPIMYSIICFVGLLGNGLVVLTYIYFKRLKTMTDTYLLNLAVADILFLLTLPFWAYSAAKSWVFGVHFCKLIFAIYKMSFFSGMLLLLCISIDRYVAIVQAVSAHRHRARVLLISKLSCVGIWILATVLSIPELLYSDLQRSSSEQAMRCSLITEHVEAFITIQVAQMVIGFLVPLLAMSFCYLVIIRTLLQARNFERNKAIKVIIAVVVVFIVFQLPYNGVVLAQTVANFNITSSTCELSKQLNIAYDVTYSLACVRCCVNPFLYAFIGVKFRNDLFKLFKDLGCLSQEQLRQWSSCRHIRRSSMSVEAETTTTFSP"""
    assert Receptor.sequence == """MMIISMWMSISRGLWDSSSIWSVLLILACMASITTSSSVSNAGYVDNGNMKVCIGTKSRLSVPSNKEHHYRNLRDRYTNCTYVDGNLELTWLPNENLDLSFLDNIREVTGYILISHVDVKKVVFPKLQIIRGRTLFSLSVEEEKYALFVTYSKMYTLEIPDLRDVLNGQVGFHNNYNLCHMRTIQWSEIVSNGTDAYYNYDFTAPERECPKCHESCTHGCWGEGPKNCQKFSKLTCSPQCAGGRCYGPKPRECCHLFCAGGCTGPTQKDCIACKNFFDEGVCKEECPPMRKYNPTTYVLETNPEGKYAYGATCVKECPGHLLRDNGACVRSCPQDKMDKGGECVPCNGPCPKTCPGVTVLHAGNIDSFRNCTVIDGNIRILDQTFSGFQDVYANYTMGPRYIPLDPERLEVFSTVKEITGYLNIEGTHPQFRNLSYFRNLETIHGRQLMESMFAALAIVKSSLYSLEMRNLKQISSGSVVIQHNRDLCYVSNIRWPAIQKEPEQKVWVNENLRADLCEKNGTICSDQCNEDGCWGAGTDQCLTCKNFNFNGTCIADCGYISNAYKFDNRTCKICHPECRTCNGAGADHCQECVHVRDGQHCVSECPKNKYNDRGVCRECHATCDGCTGPKDTIGIGACTTCNLAIINNDATVKRCLLKDDKCPDGYFWEYVHPQEQGSLKPLAGRAVCRKCHPLCELCTNYGYHEQVCSKCTHYKRREQCETECPADHYTDEEQRECFQCHPECNGCTGPGADDCKSCRNFKLFDANETGPYVNSTMFNCTSKCPLEMRHVNYQYTAIGPYCAASPPRSSKITANLDVNMIFIITGAVLVPTICILCVVTYICRQKQKAKKETVKMTMALSGCEDSEPLRPSNIGANLCKLRIVKDAELRKGGVLGMGAFGRVYKGVWVPEGENVKIPVAIKELLKSTGAESSEEFLREAYIMASVEHVNLLKLLAVCMSSQMMLITQLMPLGCLLDYVRNNRDKIGSKALLNWSTQIAKGMSYLEEKRLVHRDLAARNVLVQTPSLVKITDFGLAKLLSSDSNEYKAAGGKMPIKWLALECIRNRVFTSKSDVWAFGVTIWELLTFGQRPHENIPAKDIPDLIEVGLKLEQPEICSLDIYCTLLSCWHLDAAMRPTFKQLTTVFAEFARDPGRYLAIPGDKFTRLPAYTSQDEKDLIRKLAPTTDGSEAIAEPDDYLQPKAAPGPSHRTDCTDEIPKLNRYCKDPSNKNSSTGDDETDSSAREVGVGNLRLDLPVDEDDYLMPTCQPGPNNNNNINNPNQNNMAAVGVAAGYMDLIGVPVSVDNPEYLLNAQTLGVGESPIPTQTIGIPVMGVPGTMEVKVPMPGSEPTSSDHEYYNDTQRELQPLHRNRNTETRV"""

    all_aas = set([aa for aa in aa_df["1-letter code"]])
    assert set(GPCR.sequence).issubset(all_aas) is True
    assert set(Receptor.sequence).issubset(all_aas) is True

    assert len(GPCR.sequence) > 0
    assert len(Receptor.sequence) > 0

def test_map():
    testProtein = Protein.exercise_5.Protein(lookup)
    testProtein.sequence = "RRR"
    assert testProtein.map("hydropathy", 1) == [-4.5, -4.5, -4.5]
    assert testProtein.map("pI", 1) == [10.76, 10.76, 10.76]

    testProtein.sequence = "RRRRRRRRRR"
    for slide in range(1,9):
        assert testProtein.map("hydropathy", slide) == [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5, -4.5]

    testProtein.sequence = "RRVRR"
    assert testProtein.map("hydropathy",1) == [-4.5, -4.5, 4.2, -4.5, -4.5]
    assert testProtein.map("hydropathy", 2) == [-4.5,-4.5, -0.15, -0.15, -4.5]